version: "3"
volumes:
  postgres-data:
services:
  postgres:
    image: postgres:16.2
    shm_size: "128mb"
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRESQL_MULTIPLE_DATABASES=chinook
    ports:
      - "5432:5432"
    volumes:
      - "./docker-compose/postgres/initdb.d:/docker-entrypoint-initdb.d:Z"
      - postgres-data:/var/lib/postgresql/data
  chinook:
    profiles:
      - app
    build:
      context: ./chinook
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    network_mode: host
  kroki:
    profiles:
      - doc
    image: yuzutech/kroki:0.25.0
    ports:
      - "8000:8000"
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_SAFE_MODE=UNSAFE
  mermaid:
    profiles:
      - doc
    image: yuzutech/kroki-mermaid:0.24.1
    expose:
      - "8002"
